port 6379
bind 0.0.0.0
protected-mode no
requirepass admin123
masterauth admin123

# Persistence
save 900 1
save 300 10
save 60 10000
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

# Memory
maxmemory 2gb
maxmemory-policy allkeys-lru

# Replication
replica-read-only yes
replica-serve-stale-data yes
