port 26379
bind 0.0.0.0
protected-mode no

sentinel monitor scm-master redis 6379 2
sentinel auth-pass scm-master admin123
sentinel down-after-milliseconds scm-master 5000
sentinel failover-timeout scm-master 60000
sentinel parallel-syncs scm-master 1
