apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-auth-canary
  namespace: scm-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scm-auth
      track: canary
  template:
    metadata:
      labels:
        app: scm-auth
        track: canary
    spec:
      containers:
        - name: scm-auth
          image: ${DOCKERHUB_USERNAME}/scm-auth:canary
          ports:
            - containerPort: 8106
          envFrom:
            - configMapRef:
                name: scm-config
            - secretRef:
                name: scm-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"